# Generated by Django 3.2.5 on 2021-07-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='username',
            new_name='minecraftUsername',
        ),
    ]
