# Generated by Django 3.2.5 on 2021-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_rename_username_player_minecraftusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='additional_permissions',
            field=models.ManyToManyField(null=True, to='interface.Permissions'),
        ),
    ]
