# Generated by Django 3.2.5 on 2021-08-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_alter_player_additional_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverclient',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
