# Generated by Django 3.2.5 on 2021-08-03 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0006_player_rights_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='minecraftUsername',
            field=models.CharField(default=None, max_length=24, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=24)),
                ('content', models.TextField()),
                ('madeby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
