# Generated by Django 3.2.5 on 2021-08-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_npcplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcplayer',
            name='was_last_in',
            field=models.CharField(default='Nowhere', max_length=30),
        ),
    ]
