# Generated by Django 3.2.5 on 2021-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_npcplayer_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_by', models.CharField(max_length=20)),
                ('resolved_by', models.CharField(default='Noone', max_length=20, null=True)),
                ('content', models.TextField()),
                ('made_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('resolved_on', models.DateTimeField(null=True)),
            ],
        ),
    ]
