# Generated by Django 3.2.5 on 2021-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='made_in',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
