# Generated by Django 3.2.5 on 2021-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_report_made_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='target',
            field=models.CharField(default='Nobody', max_length=20),
        ),
    ]
